//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dios_mio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Bonificacion1 = new HashSet<Bonificacion>();
            this.RetencionISR = new HashSet<RetencionISR>();
        }
    
        public int idEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<float> Bonificacion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public string Estado { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual ICollection<Bonificacion> Bonificacion1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<RetencionISR> RetencionISR { get; set; }
    }
}
