//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dios_mio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PlanillaDBEntities : DbContext
    {
        public PlanillaDBEntities()
            : base("name=PlanillaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bonificacion> Bonificacion { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Igss> Igss { get; set; }
        public virtual DbSet<planillaSQL> planillaSQL { get; set; }
        public virtual DbSet<RetencionISR> RetencionISR { get; set; }
        public virtual DbSet<SalarioOrdinario> SalarioOrdinario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual int sp_AgregarEmpleado(string nombre, string apellido, string fechaInicio, string estado, string idusuario)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("Apellido", apellido) :
                new ObjectParameter("Apellido", typeof(string));
    
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var idusuarioParameter = idusuario != null ?
                new ObjectParameter("idusuario", idusuario) :
                new ObjectParameter("idusuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AgregarEmpleado", nombreParameter, apellidoParameter, fechaInicioParameter, estadoParameter, idusuarioParameter);
        }
    
        public virtual int sp_AgregarIgss(Nullable<int> anio, string cuotaIgss)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(int));
    
            var cuotaIgssParameter = cuotaIgss != null ?
                new ObjectParameter("CuotaIgss", cuotaIgss) :
                new ObjectParameter("CuotaIgss", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AgregarIgss", anioParameter, cuotaIgssParameter);
        }
    
        public virtual int sp_agregarRetencion(string retencionEmpleado, Nullable<int> idEmpleado)
        {
            var retencionEmpleadoParameter = retencionEmpleado != null ?
                new ObjectParameter("RetencionEmpleado", retencionEmpleado) :
                new ObjectParameter("RetencionEmpleado", typeof(string));
    
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("idEmpleado", idEmpleado) :
                new ObjectParameter("idEmpleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_agregarRetencion", retencionEmpleadoParameter, idEmpleadoParameter);
        }
    
        public virtual int sp_AgregarSalarioOrdinario(Nullable<int> anio, string cuotaSalarioOrdinario)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(int));
    
            var cuotaSalarioOrdinarioParameter = cuotaSalarioOrdinario != null ?
                new ObjectParameter("CuotaSalarioOrdinario", cuotaSalarioOrdinario) :
                new ObjectParameter("CuotaSalarioOrdinario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AgregarSalarioOrdinario", anioParameter, cuotaSalarioOrdinarioParameter);
        }
    
        public virtual ObjectResult<sp_AutenticarUsuario_Result> sp_AutenticarUsuario(string username, string userpassword)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var userpasswordParameter = userpassword != null ?
                new ObjectParameter("userpassword", userpassword) :
                new ObjectParameter("userpassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AutenticarUsuario_Result>("sp_AutenticarUsuario", usernameParameter, userpasswordParameter);
        }
    
        public virtual int sp_EliminarBonificaion(Nullable<int> idBonificacion)
        {
            var idBonificacionParameter = idBonificacion.HasValue ?
                new ObjectParameter("idBonificacion", idBonificacion) :
                new ObjectParameter("idBonificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarBonificaion", idBonificacionParameter);
        }
    
        public virtual int sp_eliminarEmpleados(Nullable<int> idEmpleado)
        {
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("idEmpleado", idEmpleado) :
                new ObjectParameter("idEmpleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_eliminarEmpleados", idEmpleadoParameter);
        }
    
        public virtual int sp_EliminarIgss(Nullable<int> idIgss)
        {
            var idIgssParameter = idIgss.HasValue ?
                new ObjectParameter("idIgss", idIgss) :
                new ObjectParameter("idIgss", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarIgss", idIgssParameter);
        }
    
        public virtual int sp_EliminarRetencion(Nullable<int> idRetencionISR)
        {
            var idRetencionISRParameter = idRetencionISR.HasValue ?
                new ObjectParameter("idRetencionISR", idRetencionISR) :
                new ObjectParameter("idRetencionISR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarRetencion", idRetencionISRParameter);
        }
    
        public virtual int sp_EliminarSalarioOrdinario(Nullable<int> idSalarioOrdinario)
        {
            var idSalarioOrdinarioParameter = idSalarioOrdinario.HasValue ?
                new ObjectParameter("idSalarioOrdinario", idSalarioOrdinario) :
                new ObjectParameter("idSalarioOrdinario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarSalarioOrdinario", idSalarioOrdinarioParameter);
        }
    
        public virtual ObjectResult<sp_listarBonificacion_Result> sp_listarBonificacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listarBonificacion_Result>("sp_listarBonificacion");
        }
    
        public virtual ObjectResult<sp_ListarEmpleados_Result> sp_ListarEmpleados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarEmpleados_Result>("sp_ListarEmpleados");
        }
    
        public virtual ObjectResult<sp_listarIgss_Result> sp_listarIgss()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listarIgss_Result>("sp_listarIgss");
        }
    
        public virtual ObjectResult<sp_ListarPlanilla_Result> sp_ListarPlanilla(Nullable<int> anio, string mes)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("Anio", anio) :
                new ObjectParameter("Anio", typeof(int));
    
            var mesParameter = mes != null ?
                new ObjectParameter("Mes", mes) :
                new ObjectParameter("Mes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarPlanilla_Result>("sp_ListarPlanilla", anioParameter, mesParameter);
        }
    
        public virtual ObjectResult<sp_listarRetencion_Result> sp_listarRetencion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listarRetencion_Result>("sp_listarRetencion");
        }
    
        public virtual ObjectResult<sp_listarSalarioOrdinario_Result> sp_listarSalarioOrdinario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listarSalarioOrdinario_Result>("sp_listarSalarioOrdinario");
        }
    
        public virtual ObjectResult<sp_ListarUsuarios_Result> sp_ListarUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarUsuarios_Result>("sp_ListarUsuarios");
        }
    
        public virtual int sp_ModificarBonificacion(Nullable<int> idBonificacion, string bonificacionEmpleado, string idEmpleado)
        {
            var idBonificacionParameter = idBonificacion.HasValue ?
                new ObjectParameter("idBonificacion", idBonificacion) :
                new ObjectParameter("idBonificacion", typeof(int));
    
            var bonificacionEmpleadoParameter = bonificacionEmpleado != null ?
                new ObjectParameter("BonificacionEmpleado", bonificacionEmpleado) :
                new ObjectParameter("BonificacionEmpleado", typeof(string));
    
            var idEmpleadoParameter = idEmpleado != null ?
                new ObjectParameter("idEmpleado", idEmpleado) :
                new ObjectParameter("idEmpleado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarBonificacion", idBonificacionParameter, bonificacionEmpleadoParameter, idEmpleadoParameter);
        }
    
        public virtual int sp_ModificarEmpleado(Nullable<int> idEmpleado, string nombre, string apellido, string estado, Nullable<int> idUsuario)
        {
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("idEmpleado", idEmpleado) :
                new ObjectParameter("idEmpleado", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarEmpleado", idEmpleadoParameter, nombreParameter, apellidoParameter, estadoParameter, idUsuarioParameter);
        }
    
        public virtual int sp_modificarIgss(Nullable<int> idIgss, Nullable<int> anio, string cuotaIgss)
        {
            var idIgssParameter = idIgss.HasValue ?
                new ObjectParameter("idIgss", idIgss) :
                new ObjectParameter("idIgss", typeof(int));
    
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(int));
    
            var cuotaIgssParameter = cuotaIgss != null ?
                new ObjectParameter("CuotaIgss", cuotaIgss) :
                new ObjectParameter("CuotaIgss", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_modificarIgss", idIgssParameter, anioParameter, cuotaIgssParameter);
        }
    
        public virtual int sp_ModificarRetencion(Nullable<int> idRetencion, string retencionEmpleado, string idEmpleado)
        {
            var idRetencionParameter = idRetencion.HasValue ?
                new ObjectParameter("idRetencion", idRetencion) :
                new ObjectParameter("idRetencion", typeof(int));
    
            var retencionEmpleadoParameter = retencionEmpleado != null ?
                new ObjectParameter("RetencionEmpleado", retencionEmpleado) :
                new ObjectParameter("RetencionEmpleado", typeof(string));
    
            var idEmpleadoParameter = idEmpleado != null ?
                new ObjectParameter("idEmpleado", idEmpleado) :
                new ObjectParameter("idEmpleado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarRetencion", idRetencionParameter, retencionEmpleadoParameter, idEmpleadoParameter);
        }
    
        public virtual int sp_modificarSalarioOrdinairo(Nullable<int> idSalarioOrdinario, Nullable<int> anio, string cuotaSalarioOrdinario)
        {
            var idSalarioOrdinarioParameter = idSalarioOrdinario.HasValue ?
                new ObjectParameter("idSalarioOrdinario", idSalarioOrdinario) :
                new ObjectParameter("idSalarioOrdinario", typeof(int));
    
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(int));
    
            var cuotaSalarioOrdinarioParameter = cuotaSalarioOrdinario != null ?
                new ObjectParameter("CuotaSalarioOrdinario", cuotaSalarioOrdinario) :
                new ObjectParameter("CuotaSalarioOrdinario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_modificarSalarioOrdinairo", idSalarioOrdinarioParameter, anioParameter, cuotaSalarioOrdinarioParameter);
        }
    }
}
